//! Render a plan into a self-contained, print-optimised HTML report.
//! Open it in a browser and "Print → Save as PDF" to get a document in the
//! style of the reference progress report.

use chrono::Utc;

use crate::git::RepoInfo;
use crate::model::{Plan, Status};
use crate::score::{stats, Stats};

/// Options that label the report header.
#[derive(Debug, Clone, Default)]
pub struct ReportMeta {
    /// Project / org line, e.g. "Geomed Pharmacy".
    pub subtitle: Option<String>,
    pub repo: RepoInfo,
}

/// Produce a full HTML document for `plan`.
pub fn render_html(plan: &Plan, meta: &ReportMeta) -> String {
    let s = stats(plan);
    let today = Utc::now().format("%Y-%m-%d");

    // Subtitle line: "<subtitle> · <branch> · as of <date>"
    let mut sub_parts: Vec<String> = Vec::new();
    if let Some(st) = &meta.subtitle {
        sub_parts.push(esc(st));
    }
    if let Some(b) = &meta.repo.branch {
        sub_parts.push(esc(b));
    }
    sub_parts.push(format!("as of {today}"));
    let subtitle = sub_parts.join(" · ");

    let mut body = String::new();
    body.push_str(&header(plan, &subtitle, &s));
    body.push_str(&groups(plan));
    body.push_str(&footer(plan, &s));

    format!(
        "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
<title>{title} — Progress Report</title>\n<style>{css}</style>\n</head>\n\
<body>\n<main class=\"report\">\n{body}</main>\n</body>\n</html>\n",
        title = esc(&plan.title),
        css = CSS,
        body = body,
    )
}

fn header(plan: &Plan, subtitle: &str, s: &Stats) -> String {
    format!(
        "<header>\n  <h1>{title} — Progress Report</h1>\n  <p class=\"subtitle\">{subtitle}</p>\n\
</header>\n\
<section class=\"tiles\">\n\
  <div class=\"tile pct\"><div class=\"n\">{pct:.1}%</div><div class=\"l\">overall (half-credit partials)</div></div>\n\
  <div class=\"tile done\"><div class=\"n\">{done}</div><div class=\"l\">items done</div></div>\n\
  <div class=\"tile partial\"><div class=\"n\">{partial}</div><div class=\"l\">items partial</div></div>\n\
  <div class=\"tile open\"><div class=\"n\">{open}</div><div class=\"l\">items open</div></div>\n\
</section>\n\
<p class=\"legend\"><span class=\"g done\">● Done</span> <span class=\"g partial\">◐ Partial</span> \
<span class=\"g open\">○ Open</span> <span class=\"g inprog\">◔ In progress</span> \
<span class=\"g blocked\">✕ Blocked</span></p>\n",
        title = esc(&plan.title),
        subtitle = subtitle,
        pct = s.percent,
        done = s.done,
        partial = s.partial,
        open = s.open_like(),
    )
}

fn groups(plan: &Plan) -> String {
    let mut out = String::from("<section class=\"detail\">\n<h2>Detail</h2>\n");
    for group in plan.group_order() {
        let tasks: Vec<_> = plan.tasks.iter().filter(|t| t.group == group).collect();
        if tasks.is_empty() {
            continue;
        }
        let gstats = Stats::of(tasks.iter().copied());
        let group_name = group.as_deref().unwrap_or("Ungrouped");
        out.push_str(&format!(
            "<div class=\"group\">\n  <div class=\"group-head\"><span class=\"gname\">{name}</span>\
<span class=\"gpct\">{pct:.0}%</span></div>\n  <ul class=\"items\">\n",
            name = esc(group_name),
            pct = gstats.percent,
        ));
        for t in tasks {
            let date = t
                .evidence
                .last()
                .map(|e| e.at.format("%Y-%m-%d").to_string())
                .unwrap_or_default();
            out.push_str(&format!(
                "    <li class=\"item {cls}\"><span class=\"dot\">{glyph}</span>\
<span class=\"txt\">{title}</span><span class=\"date\">{date}</span></li>\n",
                cls = status_class(t.status),
                glyph = t.status.glyph(),
                title = esc(&t.title),
                date = date,
            ));
        }
        out.push_str("  </ul>\n</div>\n");
    }
    out.push_str("</section>\n");
    out
}

fn footer(plan: &Plan, s: &Stats) -> String {
    let source = plan
        .source
        .as_deref()
        .map(|src| format!(" Plan source: {}.", esc(src)))
        .unwrap_or_default();
    format!(
        "<footer>\n<p>Item count is line-weighted with half-credit partials \
({total} items, weight {weight}). Treat % as a rough directional signal.{source} \
Generated by Trackly.</p>\n</footer>\n",
        total = s.total,
        weight = s.weight_total,
        source = source,
    )
}

fn status_class(status: Status) -> &'static str {
    match status {
        Status::Done => "done",
        Status::Partial => "partial",
        Status::InProgress => "inprog",
        Status::Open => "open",
        Status::Blocked => "blocked",
    }
}

/// Minimal HTML escaping for text interpolated into the report.
fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

const CSS: &str = r#"
:root {
  --ink: #1f2328; --muted: #6b7280; --line: #e5e7eb;
  --done: #1a7f37; --partial: #b45309; --open: #6b7280; --blocked: #b91c1c; --pct: #1f6feb;
  --done-bg: #eaf5ec; --partial-bg: #fbf0e2; --open-bg: #f3f4f6; --pct-bg: #eaf1fb;
}
* { box-sizing: border-box; }
/* A progress report is a printed document — always white, independent of the viewer's theme. */
html { background: #fff; }
body { margin: 0; background: #fff; color: var(--ink); font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
.report { max-width: 820px; margin: 0 auto; padding: 40px 36px; }
h1 { font-size: 26px; font-weight: 600; margin: 0 0 4px; letter-spacing: -0.01em; }
.subtitle { color: var(--muted); margin: 0 0 24px; font-size: 13px; }
.tiles { display: grid; grid-template-columns: repeat(4, 1fr); border: 1px solid var(--line); border-radius: 8px; overflow: hidden; }
.tile { padding: 18px 16px; border-right: 1px solid var(--line); text-align: left; }
.tile:last-child { border-right: 0; }
.tile .n { font-size: 30px; font-weight: 600; letter-spacing: -0.02em; }
.tile .l { color: var(--muted); font-size: 11px; margin-top: 4px; }
.tile.pct { background: var(--pct-bg); } .tile.pct .n { color: var(--pct); }
.tile.done { background: var(--done-bg); } .tile.done .n { color: var(--done); }
.tile.partial { background: var(--partial-bg); } .tile.partial .n { color: var(--partial); }
.tile.open { background: var(--open-bg); } .tile.open .n { color: var(--open); }
.legend { margin: 16px 0 28px; font-size: 12px; color: var(--muted); }
.legend .g { margin-right: 14px; white-space: nowrap; }
.legend .done { color: var(--done); } .legend .partial { color: var(--partial); }
.legend .blocked { color: var(--blocked); }
.detail h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted); font-weight: 600; margin: 0 0 12px; }
.group { margin-bottom: 22px; }
.group-head { display: flex; justify-content: space-between; align-items: baseline; border-bottom: 1px solid var(--line); padding-bottom: 6px; margin-bottom: 8px; }
.gname { font-weight: 600; font-size: 14px; }
.gpct { color: var(--muted); font-size: 12px; }
.items { list-style: none; margin: 0; padding: 0; }
.item { display: flex; align-items: baseline; gap: 10px; padding: 4px 0; }
.item .dot { width: 14px; flex: none; text-align: center; }
.item .txt { flex: 1; }
.item .date { color: var(--muted); font-size: 11px; font-variant-numeric: tabular-nums; flex: none; }
.item.done .dot { color: var(--done); } .item.partial .dot { color: var(--partial); }
.item.inprog .dot { color: var(--pct); } .item.open .dot { color: var(--open); }
.item.blocked .dot { color: var(--blocked); }
footer { margin-top: 32px; padding-top: 14px; border-top: 1px solid var(--line); color: var(--muted); font-size: 11px; }
@page { size: A4 portrait; margin: 16mm; }
@media print { .report { padding: 0; max-width: none; } .group { break-inside: avoid; } }
"#;
